version: '2'
services:
  api:
    image: quay.io/codaisseur/code-assignments
    entrypoint: ''
    environment:
      - DATABASE_URL=mongodb://mongodb:27017/
    command: npm start --no-deprecation
    depends_on:
      - mongodb
    ports:
      - "5000:5000"

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
